# -*- coding: utf-8 -*-
"""Copy of 2024E_PROJECT UAS DATA WRANGLING KELOMPOK 2 (FIXED).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OOdIPm5W4vTfMXszrdxWiC_GKGDDhIxH

**PROJECT UAS MATA KULIAH DATA WRANGLING "ANALISIS TREN JUMLAH PENUMPANG PESAWAT DOMESTIK DI 5 BANDARA UTAMA INDONEISA TAHUN 2020-2025"**

Disusun Oleh Kelompok 2 Kelas 2024E:
1. Andika Febrianto (24031554018)
2. Dista Ishlahul Amalia (24031554063)


Dosen Pembimbing:
Ike Fitriyaningsih, M.Si


Sumber Data (BPS): https://www.bps.go.id/id/statistics-table/2/MjM0OSMy/jumlah-penumpang-pesawat--angkutan-udara--domestik-di-5-bandara-utama--orang-.html

TEKNIK PENGAMBILAN DAN BACA DATASET
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df1 = pd.read_csv("/content/Jumlah Penumpang Pesawat (Angkutan Udara) Domestik di 5 Bandara Utama, 2020.csv")
df1

df2 = pd.read_csv("/content/Jumlah Penumpang Pesawat (Angkutan Udara) Domestik di 5 Bandara Utama, 2021.csv")
df2

df3 = pd.read_csv("/content/Jumlah Penumpang Pesawat (Angkutan Udara) Domestik di 5 Bandara Utama, 2022.csv")
df3

df4 = pd.read_csv("/content/Jumlah Penumpang Pesawat (Angkutan Udara) Domestik di 5 Bandara Utama, 2023.csv")
df4

df5 = pd.read_csv("/content/Jumlah Penumpang Pesawat (Angkutan Udara) Domestik di 5 Bandara Utama, 2024.csv")
df5

df6 = pd.read_csv("/content/Jumlah Penumpang Pesawat (Angkutan Udara) Domestik di 5 Bandara Utama, 2025.csv")
df6

"""INTEGRASI DATA"""

import pandas as pd

# Membaca semua isi file dataset
files = [
    "Jumlah Penumpang Pesawat (Angkutan Udara) Domestik di 5 Bandara Utama, 2020.csv",
    "Jumlah Penumpang Pesawat (Angkutan Udara) Domestik di 5 Bandara Utama, 2021.csv",
    "Jumlah Penumpang Pesawat (Angkutan Udara) Domestik di 5 Bandara Utama, 2022.csv",
    "Jumlah Penumpang Pesawat (Angkutan Udara) Domestik di 5 Bandara Utama, 2023.csv",
    "Jumlah Penumpang Pesawat (Angkutan Udara) Domestik di 5 Bandara Utama, 2024.csv",
    "Jumlah Penumpang Pesawat (Angkutan Udara) Domestik di 5 Bandara Utama, 2025.csv"
]

dfs = []

for file in files:
    # Membaca semua baris isi file dataset
    df = pd.read_csv(file, header=None)

    # Mengubah semua header "Unnamed" menjadi string kosong
    df.columns = [
        "" if str(c).startswith("Unnamed") else str(c)
        for c in df.columns
    ]

    # Menghapus baris yang kosong
    df = df.dropna(how="all")

    dfs.append(df)

# Concatenate (Menggabungkan) seluruh dataframe
df_all = pd.concat(dfs, ignore_index=True)

# Menyimpan file integrasi
output_path = "Hasil_Integrasi.csv"
df_all.to_csv(output_path, index=False, header=True, encoding="utf-8-sig")

print("", output_path)
print("Jumlah baris:", len(df_all))
print("Jumlah kolom:", len(df_all.columns))

df = pd.read_csv("/content/Hasil_Integrasi.csv")
df

"""CLEANING HASIL INTEGRASI"""

import pandas as pd
import numpy as np
import os
import re

input_file = "Hasil_Integrasi.csv"
output_file = "Dataset_Penumpang_Clean.csv"

# Nama bulan
MONTHS_ID = ["Januari","Februari","Maret","April","Mei","Juni",
             "Juli","Agustus","September","Oktober","November","Desember"]

# Membersihkan spasi, koma, titik, (-)
def clean_num(x):
    if pd.isna(x) or str(x).strip() == "":
        return 0
    s = str(x).strip().replace(",", "").replace(".", "").replace(" ", "")
    if re.fullmatch(r'[-–—]+', s):
        return 0
    return int(re.sub(r'[^\d\-]', '', s) or 0)

# Parsing file hasil integrasi
def parse_integrated_file(path):
    df_raw = pd.read_csv(path, header=None, dtype=str, keep_default_na=False)
    nrows, ncols = df_raw.shape
    all_records = []

    # Blok kolom tiap kategori
    # Tiap blok terdiri dari 13 kolom yaitu 12 bulan + tahunan
    category_col_blocks = {
        "Keberangkatan": (1, 13),
        "Kedatangan": (14, 26),
        "Transit": (27, 39)
    }

    r_idx = 0
    while r_idx < nrows:
        col1_val = str(df_raw.iat[r_idx, 1]).strip()
        if col1_val.isdigit() and len(col1_val) == 4:
            tahun = int(col1_val)
            data_start = r_idx + 2
            data_end = min(data_start + 6, nrows)

            for dr in range(data_start, data_end):
                airport = str(df_raw.iat[dr, 0]).strip()
                if not airport or airport.lower() in ["nan","none","total","jumlah"]:
                    continue

                # ambil data tiap kategori
                for cat, (start_col, end_col) in category_col_blocks.items():
                    rec = {"bandara": airport, "kategori": cat, "tahun": tahun}
                    for m in MONTHS_ID + ["Tahunan"]:
                        rec[m] = 0

                    month_counter = 0
                    for c in range(start_col, end_col+1):
                        if c < ncols:
                            month_name = None
                            if month_counter < len(MONTHS_ID):
                                month_name = MONTHS_ID[month_counter]
                            elif month_counter == len(MONTHS_ID):
                                month_name = "Tahunan"
                            if month_name:
                                rec[month_name] = clean_num(df_raw.iat[dr, c])
                                month_counter += 1
                        else:
                            break
                    all_records.append(rec)
            r_idx += 12
            continue
        r_idx += 1

    if not all_records:
        print("Ga ada data yang ke-parse, cek file atau logikanya")
        return pd.DataFrame()

    df_parsed = pd.DataFrame(all_records)
    cols_order = ["bandara","kategori","tahun"] + MONTHS_ID + ["Tahunan"]
    for c in cols_order:
        if c not in df_parsed.columns:
            df_parsed[c] = 0
    df_parsed = df_parsed[cols_order]

    # Normalisasi nama bandara
    df_parsed["bandara"] = df_parsed["bandara"].astype(str).str.replace(r"(?i)\s+Medan$", "", regex=True).str.strip()
    df_parsed["bandara"] = df_parsed["bandara"].replace({
        r"(?i)soekarno[\s\-]?hatta|soetta": "Soekarno-Hatta",
        r"(?i)juanda": "Juanda",
        r"(?i)kualanamu": "Kualanamu",
        r"(?i)sultan\s+hasanuddin": "Sultan Hasanuddin",
        r"(?i)(i\s+gusti\s+ngurah\s+rai|ngurah\s+rai|ngurahrai)": "Ngurah Rai"
    }, regex=True)
    return df_parsed

# Perhitungan statistics
df_raw_integrated = pd.read_csv(input_file, header=None)
missing_before = df_raw_integrated.isna().sum()
duplicates_before = df_raw_integrated.duplicated().sum()

df_clean = parse_integrated_file(input_file)

if not df_clean.empty:
    missing_after = df_clean.isna().sum()
    duplicates_after = df_clean.duplicated().sum()

    # Cek outliers per bulan
    outlier_after = {}
    for m in MONTHS_ID:
        if m in df_clean.columns:
            col = df_clean[m]
            mean, std = col.mean(), col.std()
            outlier_after[m] = col[(col > mean + 3*std) | (col < mean - 3*std)].count()

    bandara_unique_before = df_raw_integrated[0].nunique()
    kategori_unique_before = df_raw_integrated[1].nunique()
    bandara_unique_after = df_clean['bandara'].nunique()
    kategori_unique_after = df_clean['kategori'].nunique()

    os.makedirs(os.path.dirname(output_file) or ".", exist_ok=True)
    df_clean.to_csv(output_file, index=False)


    print(" Missing Values ")
    print("Sebelum:", missing_before)
    print("Sesudah:", missing_after)

    print("\n Duplicates ")
    print("Sebelum:", duplicates_before)
    print("Sesudah:", duplicates_after)

    print("\n Outliers per bulan ")
    for m, count in outlier_after.items():
        print(f"{m}: {count}")

    print("\n Bandara atau Kategori unik ")
    print("Bandara unik sebelum:", bandara_unique_before)
    print("Kategori unik sebelum:", kategori_unique_before)
    print("Bandara unik setelah:", bandara_unique_after)
    print("Kategori unik setelah:", kategori_unique_after)

    print("\nFile hasil cleaning:", output_file)
    print("Ukuran df:", df_clean.shape)
    print(df_clean.head())
else:
    print("Error: df_clean kosong, cek input atau logikanya")
    print("Ukuran df: (0,0)")

df = pd.read_csv("Dataset_Penumpang_Clean.csv")
df

"""VISUALISASI HASIL CLEANING"""

df = pd.read_csv("Dataset_Penumpang_Clean.csv")

import pandas as pd
import matplotlib.pyplot as plt
from ipywidgets import interact, widgets
from IPython.display import display

# Menggunakan Dataset
df = df_clean.copy()

# Memastikan kolom bulanan menjadi numerik
for col in MONTHS_ID + ["Tahunan"]:
    df[col] = df[col].apply(clean_num)

# Plotting
def plot_bandara(selected_tahun, selected_bandara, selected_kategori):
    df_plot = df[
        (df['tahun'] == selected_tahun) &
        (df['bandara'] == selected_bandara) &
        (df['kategori'] == selected_kategori)
    ]

    if df_plot.empty:
        print("Tidak ada data untuk filter yang dipilih.")
        return

    y_values = df_plot[MONTHS_ID].values.flatten()

    plt.figure(figsize=(10,5))
    plt.plot(MONTHS_ID, y_values, marker='o', linestyle='-', color='b')
    plt.title(f"Jumlah Penumpang per Bulan\n{selected_bandara} - {selected_kategori} ({selected_tahun})")
    plt.xlabel("Bulan")
    plt.ylabel("Jumlah Penumpang")
    plt.grid(True)
    plt.xticks(rotation=45)
    plt.show()

# Widgets
tahun_widget = widgets.Dropdown(
    options=sorted(df['tahun'].unique()),
    description='Tahun:'
)

bandara_widget = widgets.Dropdown(
    options=sorted(df['bandara'].unique()),
    description='Bandara:'
)

kategori_widget = widgets.Dropdown(
    options=sorted(df['kategori'].unique()),
    description='Kategori:'
)

interact(plot_bandara, selected_tahun=tahun_widget, selected_bandara=bandara_widget, selected_kategori=kategori_widget)

"""EDA"""

! pip install category_encoders

"""Import Software"""

#Read system parameter
import sys

#multidimensional arrays
import numpy as np

#manipulation and analyze data
import pandas as pd

#advance math function
import scipy as sp
from scipy import stats

#visualization
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

#warnings
import warnings
warnings.filterwarnings('ignore')

#Summary versions
print("Libraries used in this project:")
print('- Python:', sys.version)
print('- Numpy:', np.__version__)
print('- Pandas:', pd.__version__)
print('- Scipy:', sp.__version__)
print('- Matplotlib:', matplotlib.__version__)
print('- Seaborn:', sns.__version__)

"""Load and preview the data cleaned"""

df = pd.read_csv("Dataset_Penumpang_Clean.csv")
df

"""Check the shape of data"""

print("Shape:", df.shape)
df

"""Check the data types"""

df.info()

"""Mengelompokkan kolom berdasarkan tipe (Numerik dan Object)"""

df.columns.to_series().groupby(df.dtypes).groups

"""Check for correlations"""

df_clean.select_dtypes(include=['number', 'int']).corr().abs()

"""Mendefinisikan Kolom Bulan"""

MONTHS = ["Januari","Februari","Maret","April","Mei","Juni",
          "Juli","Agustus","September","Oktober","November","Desember"]

NUM_COLS = MONTHS + ["Tahunan"]

"""Generate Summary Statistics"""

df[NUM_COLS].describe().T

"""Skewness dan Kurtosis untuk semua kolom bulanan"""

skewness = df[NUM_COLS].skew()
kurtosis = df[NUM_COLS].kurtosis()

print("Skewness:\n", skewness)
print("\nKurtosis:\n", kurtosis)

"""Missing values analysis"""

df.isna().sum()

"""Remove feature with high missing"""

missing_percent = df.isna().mean() * 100
missing_percent

"""Plot histogram for all numerical columns"""

df[NUM_COLS].hist(figsize=(16,12), bins=10)
plt.tight_layout()
plt.show()

"""Boxplot untuk melihat outlier per tahun"""

plt.figure(figsize=(10,5))
sns.boxplot(data=df, x="tahun", y="Tahunan")
plt.title("Boxplot Total Penumpang per Tahun")
plt.show()

"""Line plot per tahun untuk melihat trend total penumpang 2020-2025"""

pivot_tahun = df.groupby("tahun")["Tahunan"].sum()

plt.figure(figsize=(12,6))
plt.plot(pivot_tahun.index, pivot_tahun.values, marker="o")
plt.title("Tren Penumpang Tahunan (2020–2025)")
plt.xlabel("Tahun")
plt.ylabel("Total Penumpang")
plt.grid(True)
plt.show()

"""Line plot bulanan untuk melihat rata-rata per bulan dari 2020-2025"""

avg_month = df[MONTHS].mean()

plt.figure(figsize=(15,6))
plt.plot(avg_month.index, avg_month.values, marker="o")
plt.title("Rata-Rata Penumpang per Bulan (dari 2020–2025)")
plt.xlabel("Bulan")
plt.ylabel("Jumlah Penumpang")
plt.grid(True)
plt.show()

"""Bar chart total per bandara"""

plt.figure(figsize=(12,6))
df.groupby("bandara")["Tahunan"].sum().sort_values().plot(kind="bar")
plt.title("Total Penumpang per Bandara (2020–2025)")
plt.ylabel("Jumlah")
plt.show()

"""Heatmap correlations"""

plt.figure(figsize=(12,8))
corr = df[NUM_COLS].corr()
sns.heatmap(corr, annot=False, cmap="coolwarm")
plt.title("Correlation Heatmap (Kolom Bulanan & Tahunan)")
plt.show()

"""Format heatmap untuk lebih mudah dibaca"""

plt.figure(figsize=(14,10))
sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm", linewidths=.5)
plt.title("Formatted Heatmap with Correlation Values")
plt.show()

"""Analysis jumlah penumpang per kategori"""

plt.figure(figsize=(10,5))
df.groupby("kategori")["Tahunan"].sum().sort_values().plot(kind="bar", color="steelblue")
plt.title("Total Penumpang per Kategori (2020–2025)")
plt.ylabel("Jumlah")
plt.xlabel("Kategori")
plt.show()

"""Tren per kategori"""

pivot_kategori = df.groupby(["tahun","kategori"])["Tahunan"].sum().unstack()

pivot_kategori.plot(figsize=(12,6), marker="o")
plt.title("Tren Penumpang per Kategori (2020–2025)")
plt.xlabel("Tahun")
plt.ylabel("Jumlah Penumpang")
plt.grid(True)
plt.show()

"""Total penumpang semua bandara"""

plt.figure(figsize=(12,6))
df.groupby("bandara")["Tahunan"].sum().plot(kind="bar", color="salmon")
plt.title("Total Penumpang per Bandara (2020–2025)")
plt.ylabel("Jumlah Penumpang")
plt.xlabel("Bandara")
plt.xticks(rotation=45)
plt.show()

"""Tren tahunan semua bandara"""

df_bandara = df.pivot_table(values="Tahunan", index="tahun", columns="bandara", aggfunc="sum")

df_bandara.plot(figsize=(14,7), marker="o")
plt.title("Tren Penumpang per Bandara (2020–2025)")
plt.xlabel("Tahun")
plt.ylabel("Jumlah Penumpang")
plt.grid(True)
plt.show()

"""Kenaikan dari tahun ke tahun"""

df_growth = df.groupby("tahun")["Tahunan"].sum().pct_change() * 100
df_growth

plt.figure(figsize=(10,5))
plt.plot(df_growth.index, df_growth.values, marker="o", color="green")
plt.title("Kenaikan dari tahun ke tahun (%)")
plt.xlabel("Tahun")
plt.ylabel("Growth (%)")
plt.grid(True)
plt.show()

"""Kenaikan rata-rata setiap bulannya"""

monthly_avg = df[MONTHS].mean()
monthly_growth = monthly_avg.pct_change() * 100
monthly_growth

plt.figure(figsize=(15,6))
plt.plot(monthly_growth.index, monthly_growth.values, marker="o", color="purple")
plt.title("Rata-Rata Bulanan (2020–2025)")
plt.ylabel("Growth (%)")
plt.grid(True)
plt.show()

"""Anomaly detection"""

outliers = {}
for col in NUM_COLS:
    z = np.abs(stats.zscore(df[col]))
    outliers[col] = df[z > 3][col].values

outliers

"""Plot outlier untuk tahunan"""

z = np.abs(stats.zscore(df["Tahunan"]))
df_out = df[z > 3]

plt.figure(figsize=(12,6))
plt.plot(df["tahun"], df["Tahunan"], marker="o", label="Normal")
plt.scatter(df_out["tahun"], df_out["Tahunan"], color="red", s=100, label="Outlier")
plt.legend()
plt.title("Outlier Detection pada Total Penumpang")
plt.show()

"""Analysis musiman"""

monthly_mean = df[MONTHS].mean()

plt.figure(figsize=(15,5))
sns.lineplot(x=MONTHS, y=monthly_mean.values, marker="o")
plt.title("Pola Musiman Penumpang per Bulan")
plt.ylabel("Rata-rata Jumlah Penumpang")
plt.grid(True)
plt.show()

"""Multi plot bulanan"""

fig, axes = plt.subplots(3, 4, figsize=(20,12))
axes = axes.flatten()

for i, col in enumerate(MONTHS):
    sns.histplot(df[col], kde=True, ax=axes[i])
    axes[i].set_title(f"Distribusi {col}")

plt.tight_layout()
plt.show()

"""Menyimpan hasil EDA"""

pivot_tahun.to_csv("EDA_Tahunan.csv")

df = pd.read_csv("EDA_Tahunan.csv")
df
